name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fool GH Pages?
        run: mkdir docs

      - name: Build
        uses: andstor/jsdoc-action@v1.2
        with:
          source_dir: ./src
          recurse: true
          config_file: docs-src/jsdoc.json
          template_dir: node_modules/better-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
